# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('heading_text', models.CharField(max_length=48)),
                ('message_text', models.TextField()),
                ('button_text', models.CharField(max_length=36)),
            ],
        ),
    ]
