# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencymodal',
            name='button_text',
            field=models.CharField(help_text='Up to 48 characters', max_length=48),
        ),
        migrations.AlterField(
            model_name='emergencymodal',
            name='heading_text',
            field=models.CharField(help_text='Up to 48 characters', max_length=48),
        ),
    ]
