# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170226_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('place_name', models.CharField(max_length=48)),
                ('check_in', models.DateField()),
                ('night_count', models.IntegerField()),
                ('currency_symbol', models.CharField(max_length=1)),
                ('absolute_saving', models.FloatField()),
                ('percentage_saving', models.FloatField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
